ALTER TABLE chess_games_info
ADD COLUMN av_opening_mobility_inc FLOAT DEFAULT -1,
ADD COLUMN av_opening_mobility_dec FLOAT DEFAULT -1,
ADD COLUMN av_opening_king_safety FLOAT DEFAULT -1,
ADD COLUMN av_opening_king_openness FLOAT DEFAULT -1,
ADD COLUMN av_opening_knight_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_opening_bishop_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_opening_rook_queen_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_opening_control FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_mobility_inc FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_mobility_dec FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_king_safety FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_king_openness FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_knight_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_bishop_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_endgame_rook_queen_activ_coeff FLOAT DEFAULT -1,
ADD COLUMN av_mittelspiel_control FLOAT DEFAULT -1,
ADD COLUMN av_endgame_control FLOAT DEFAULT -1;